/* bancode_trap.c - Kernel Security Trap Damage Control Dispatch */
/* AUTO-GENERATED by generate_bindings.py - DO NOT EDIT */
/*
 * Fixed-size dispatch table for the 15 Kernel Security Trap slots
 * (0x7FFFFFF0-0x7FFFFFFE), each governing a cluster of 128 B+ BANcodes.
 *
 * Zero standard library dependencies; no dynamic allocation.
 */

#include "bancode/bancode_all.h"

static bancode_trap_handler_t g_handlers[BANCODE_TRAP_SLOT_COUNT];
static void*                  g_contexts[BANCODE_TRAP_SLOT_COUNT];
static bool                   g_installed[BANCODE_TRAP_SLOT_COUNT];
static bancode_trap_diagnostic_t g_last_dispatch = { false, 0, 0, 0 };

static bool slot_valid(uint32_t slot) {
    return slot < (uint32_t)BANCODE_TRAP_SLOT_COUNT;
}

bool bancode_trap_register_handler(uint32_t slot, bancode_trap_handler_t handler, void* context) {
    if (!slot_valid(slot) || handler == NULL) {
        return false;
    }
    g_handlers[slot]  = handler;
    g_contexts[slot]  = context;
    g_installed[slot] = true;
    return true;
}

bool bancode_trap_unregister_handler(uint32_t slot) {
    if (!slot_valid(slot) || !g_installed[slot]) {
        return false;
    }
    g_installed[slot]  = false;
    g_handlers[slot]   = NULL;
    g_contexts[slot]   = NULL;
    return true;
}

bool bancode_trap_handler_installed(uint32_t slot, void** out_context) {
    if (!slot_valid(slot)) {
        return false;
    }
    if (out_context) {
        *out_context = g_contexts[slot];
    }
    return g_installed[slot];
}

void bancode_trap_clear_all(void) {
    for (uint32_t i = 0; i < (uint32_t)BANCODE_TRAP_SLOT_COUNT; i++) {
        g_installed[i] = false;
        g_handlers[i]  = NULL;
        g_contexts[i]  = NULL;
    }
    g_last_dispatch.fired = false;
}

bool bancode_trap_dispatch(bancode_t bancode_cp) {
    g_last_dispatch.fired = false;

    /* Only fatal B+ BANcodes route to Kernel Security Traps */
    if (!bancode_is_bancode(bancode_cp)) {
        return false;
    }

    /* App mode: fatal BANcodes bypass kernel dispatch entirely and instead
     * crash the app via the registered App-level crash handler. This keeps
     * the kernel trap machinery (which is reserved for the krnl) unused by
     * application code. */
    if (bancode_is_app_mode()) {
        return bancode_app_dispatch_fatal(bancode_cp);
    }

    uint32_t slot = (uint32_t)((bancode_cp - BANCODE_BANCODE_START) / BANCODE_BANCODES_PER_TRAP);
    if (!slot_valid(slot)) {
        return false; /* slot 15 (0x0011A780-0x0011A7FF) has no trap handler */
    }
    if (!g_installed[slot]) {
        return false;
    }

    bancode_t trap_cp = (bancode_t)(BANCODE_KERNEL_TRAP_MIN + slot);

    g_last_dispatch.fired      = true;
    g_last_dispatch.slot       = slot;
    g_last_dispatch.trap_cp    = trap_cp;
    g_last_dispatch.bancode_cp = bancode_cp;

    g_handlers[slot](trap_cp, bancode_cp, g_contexts[slot]);
    return true;
}

bancode_trap_diagnostic_t bancode_trap_last_dispatch(void) {
    return g_last_dispatch;
}
