/* bancode.c - BANcode Framework implementation */
/* AUTO-GENERATED by generate_bindings.py - DO NOT EDIT */

#include "bancode/bancode_all.h"

typedef struct bancode_entry {
    bancode_t code;
    const char* name;
    const char* desc;
    const char* category;
} bancode_entry;

/* No codes assigned yet - placeholder row keeps the table valid; size is 0 so it is never matched */
static const bancode_entry bancode_table[1] = { { 0xFFFFFFFFU, "UNASSIGNED", "", "" } };
#define BANCODE_TABLE_SIZE 0

static const bancode_entry* bancode_find(bancode_t code) {
    int lo = 0;
    int hi = (int)BANCODE_TABLE_SIZE - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        if (bancode_table[mid].code == code) return &bancode_table[mid];
        if (bancode_table[mid].code < code) lo = mid + 1;
        else hi = mid - 1;
    }
    return (const bancode_entry*)0;
}

bool bancode_is_valid(bancode_t code) {
    return bancode_find(code) != (const bancode_entry*)0;
}

const char* bancode_name(bancode_t code) {
    const bancode_entry* e = bancode_find(code);
    return e ? e->name : "UNKNOWN";
}

const char* bancode_desc(bancode_t code) {
    const bancode_entry* e = bancode_find(code);
    return e ? e->desc : "";
}

const char* bancode_category(bancode_t code) {
    const bancode_entry* e = bancode_find(code);
    return e ? e->category : "";
}
